[tool.poetry]
name = "pybotx-smart-logger"
version = "0.6.7"
description = "Shows logs when you need it"
authors = ["Alexander Samoylenko <alexandr.samojlenko@ccsteam.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"

pybotx = ">=0.32.0,<0.40.0"

fastapi = ">=0.70.0,<0.75.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
